FROM azul/zulu-openjdk:8u144

RUN java -version && mkdir -pv /opt/mochi-db/log/
RUN apt-get update && apt-get install -y telnet net-tools netcat
COPY mochi-db-*.jar /opt/mochi-db/
RUN ls -la /opt/mochi-db/

# Http port
EXPOSE 8080
# Mochi communication
EXPOSE 8081
CMD java -jar /opt/mochi-db/mochi-db-*.jar
