// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/edu/stanford/cs244b/mochi/server/messages/MochiProtocol.proto

package edu.stanford.cs244b.mochi.server.messages;

public final class MochiProtocol {
  private MochiProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloToServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.stanford.cs244b.mochi.server.messages.HelloToServer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msg = 1;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code edu.stanford.cs244b.mochi.server.messages.HelloToServer}
   */
  public  static final class HelloToServer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.stanford.cs244b.mochi.server.messages.HelloToServer)
      HelloToServerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloToServer.newBuilder() to construct.
    private HelloToServer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloToServer() {
      msg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloToServer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_HelloToServer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_HelloToServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.class, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 1;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer)) {
        return super.equals(obj);
      }
      edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer other = (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) obj;

      boolean result = true;
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.stanford.cs244b.mochi.server.messages.HelloToServer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.stanford.cs244b.mochi.server.messages.HelloToServer)
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_HelloToServer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_HelloToServer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.class, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.Builder.class);
      }

      // Construct using edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_HelloToServer_descriptor;
      }

      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer getDefaultInstanceForType() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.getDefaultInstance();
      }

      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer build() {
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer buildPartial() {
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer result = new edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer(this);
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) {
          return mergeFrom((edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer other) {
        if (other == edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.getDefaultInstance()) return this;
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:edu.stanford.cs244b.mochi.server.messages.HelloToServer)
    }

    // @@protoc_insertion_point(class_scope:edu.stanford.cs244b.mochi.server.messages.HelloToServer)
    private static final edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer();
    }

    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloToServer>
        PARSER = new com.google.protobuf.AbstractParser<HelloToServer>() {
      public HelloToServer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HelloToServer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloToServer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloToServer> getParserForType() {
      return PARSER;
    }

    public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HelloFromServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.stanford.cs244b.mochi.server.messages.HelloFromServer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msg = 1;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>string clientMsg = 2;</code>
     */
    java.lang.String getClientMsg();
    /**
     * <code>string clientMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientMsgBytes();
  }
  /**
   * Protobuf type {@code edu.stanford.cs244b.mochi.server.messages.HelloFromServer}
   */
  public  static final class HelloFromServer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.stanford.cs244b.mochi.server.messages.HelloFromServer)
      HelloFromServerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloFromServer.newBuilder() to construct.
    private HelloFromServer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloFromServer() {
      msg_ = "";
      clientMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloFromServer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              clientMsg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_HelloFromServer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_HelloFromServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.class, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 1;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object clientMsg_;
    /**
     * <code>string clientMsg = 2;</code>
     */
    public java.lang.String getClientMsg() {
      java.lang.Object ref = clientMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string clientMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientMsgBytes() {
      java.lang.Object ref = clientMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg_);
      }
      if (!getClientMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientMsg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg_);
      }
      if (!getClientMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer)) {
        return super.equals(obj);
      }
      edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer other = (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) obj;

      boolean result = true;
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && getClientMsg()
          .equals(other.getClientMsg());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + CLIENTMSG_FIELD_NUMBER;
      hash = (53 * hash) + getClientMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.stanford.cs244b.mochi.server.messages.HelloFromServer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.stanford.cs244b.mochi.server.messages.HelloFromServer)
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_HelloFromServer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_HelloFromServer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.class, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.Builder.class);
      }

      // Construct using edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msg_ = "";

        clientMsg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_HelloFromServer_descriptor;
      }

      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer getDefaultInstanceForType() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.getDefaultInstance();
      }

      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer build() {
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer buildPartial() {
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer result = new edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer(this);
        result.msg_ = msg_;
        result.clientMsg_ = clientMsg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) {
          return mergeFrom((edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer other) {
        if (other == edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.getDefaultInstance()) return this;
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (!other.getClientMsg().isEmpty()) {
          clientMsg_ = other.clientMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 1;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientMsg_ = "";
      /**
       * <code>string clientMsg = 2;</code>
       */
      public java.lang.String getClientMsg() {
        java.lang.Object ref = clientMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientMsgBytes() {
        java.lang.Object ref = clientMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientMsg = 2;</code>
       */
      public Builder setClientMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientMsg = 2;</code>
       */
      public Builder clearClientMsg() {
        
        clientMsg_ = getDefaultInstance().getClientMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string clientMsg = 2;</code>
       */
      public Builder setClientMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientMsg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:edu.stanford.cs244b.mochi.server.messages.HelloFromServer)
    }

    // @@protoc_insertion_point(class_scope:edu.stanford.cs244b.mochi.server.messages.HelloFromServer)
    private static final edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer();
    }

    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloFromServer>
        PARSER = new com.google.protobuf.AbstractParser<HelloFromServer>() {
      public HelloFromServer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HelloFromServer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloFromServer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloFromServer> getParserForType() {
      return PARSER;
    }

    public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProtocolMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.stanford.cs244b.mochi.server.messages.ProtocolMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
     */
    boolean hasHelloToServer();
    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
     */
    edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer getHelloToServer();
    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
     */
    edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServerOrBuilder getHelloToServerOrBuilder();

    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
     */
    boolean hasHelloFromServer();
    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
     */
    edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer getHelloFromServer();
    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
     */
    edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServerOrBuilder getHelloFromServerOrBuilder();

    /**
     * <code>int64 msgTimestamp = 3;</code>
     */
    long getMsgTimestamp();

    public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage.Msg111Case getMsg111Case();
  }
  /**
   * Protobuf type {@code edu.stanford.cs244b.mochi.server.messages.ProtocolMessage}
   */
  public  static final class ProtocolMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.stanford.cs244b.mochi.server.messages.ProtocolMessage)
      ProtocolMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtocolMessage.newBuilder() to construct.
    private ProtocolMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtocolMessage() {
      msgTimestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtocolMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.Builder subBuilder = null;
              if (msg111Case_ == 1) {
                subBuilder = ((edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) msg111_).toBuilder();
              }
              msg111_ =
                  input.readMessage(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) msg111_);
                msg111_ = subBuilder.buildPartial();
              }
              msg111Case_ = 1;
              break;
            }
            case 18: {
              edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.Builder subBuilder = null;
              if (msg111Case_ == 2) {
                subBuilder = ((edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) msg111_).toBuilder();
              }
              msg111_ =
                  input.readMessage(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) msg111_);
                msg111_ = subBuilder.buildPartial();
              }
              msg111Case_ = 2;
              break;
            }
            case 24: {

              msgTimestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_ProtocolMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_ProtocolMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage.class, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage.Builder.class);
    }

    private int msg111Case_ = 0;
    private java.lang.Object msg111_;
    public enum Msg111Case
        implements com.google.protobuf.Internal.EnumLite {
      HELLOTOSERVER(1),
      HELLOFROMSERVER(2),
      MSG111_NOT_SET(0);
      private final int value;
      private Msg111Case(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Msg111Case valueOf(int value) {
        return forNumber(value);
      }

      public static Msg111Case forNumber(int value) {
        switch (value) {
          case 1: return HELLOTOSERVER;
          case 2: return HELLOFROMSERVER;
          case 0: return MSG111_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public Msg111Case
    getMsg111Case() {
      return Msg111Case.forNumber(
          msg111Case_);
    }

    public static final int HELLOTOSERVER_FIELD_NUMBER = 1;
    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
     */
    public boolean hasHelloToServer() {
      return msg111Case_ == 1;
    }
    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
     */
    public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer getHelloToServer() {
      if (msg111Case_ == 1) {
         return (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) msg111_;
      }
      return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.getDefaultInstance();
    }
    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
     */
    public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServerOrBuilder getHelloToServerOrBuilder() {
      if (msg111Case_ == 1) {
         return (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) msg111_;
      }
      return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.getDefaultInstance();
    }

    public static final int HELLOFROMSERVER_FIELD_NUMBER = 2;
    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
     */
    public boolean hasHelloFromServer() {
      return msg111Case_ == 2;
    }
    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
     */
    public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer getHelloFromServer() {
      if (msg111Case_ == 2) {
         return (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) msg111_;
      }
      return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.getDefaultInstance();
    }
    /**
     * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
     */
    public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServerOrBuilder getHelloFromServerOrBuilder() {
      if (msg111Case_ == 2) {
         return (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) msg111_;
      }
      return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.getDefaultInstance();
    }

    public static final int MSGTIMESTAMP_FIELD_NUMBER = 3;
    private long msgTimestamp_;
    /**
     * <code>int64 msgTimestamp = 3;</code>
     */
    public long getMsgTimestamp() {
      return msgTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msg111Case_ == 1) {
        output.writeMessage(1, (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) msg111_);
      }
      if (msg111Case_ == 2) {
        output.writeMessage(2, (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) msg111_);
      }
      if (msgTimestamp_ != 0L) {
        output.writeInt64(3, msgTimestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msg111Case_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) msg111_);
      }
      if (msg111Case_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) msg111_);
      }
      if (msgTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, msgTimestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage)) {
        return super.equals(obj);
      }
      edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage other = (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage) obj;

      boolean result = true;
      result = result && (getMsgTimestamp()
          == other.getMsgTimestamp());
      result = result && getMsg111Case().equals(
          other.getMsg111Case());
      if (!result) return false;
      switch (msg111Case_) {
        case 1:
          result = result && getHelloToServer()
              .equals(other.getHelloToServer());
          break;
        case 2:
          result = result && getHelloFromServer()
              .equals(other.getHelloFromServer());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgTimestamp());
      switch (msg111Case_) {
        case 1:
          hash = (37 * hash) + HELLOTOSERVER_FIELD_NUMBER;
          hash = (53 * hash) + getHelloToServer().hashCode();
          break;
        case 2:
          hash = (37 * hash) + HELLOFROMSERVER_FIELD_NUMBER;
          hash = (53 * hash) + getHelloFromServer().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.stanford.cs244b.mochi.server.messages.ProtocolMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.stanford.cs244b.mochi.server.messages.ProtocolMessage)
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_ProtocolMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_ProtocolMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage.class, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage.Builder.class);
      }

      // Construct using edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgTimestamp_ = 0L;

        msg111Case_ = 0;
        msg111_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.internal_static_edu_stanford_cs244b_mochi_server_messages_ProtocolMessage_descriptor;
      }

      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage getDefaultInstanceForType() {
        return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage.getDefaultInstance();
      }

      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage build() {
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage buildPartial() {
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage result = new edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage(this);
        if (msg111Case_ == 1) {
          if (helloToServerBuilder_ == null) {
            result.msg111_ = msg111_;
          } else {
            result.msg111_ = helloToServerBuilder_.build();
          }
        }
        if (msg111Case_ == 2) {
          if (helloFromServerBuilder_ == null) {
            result.msg111_ = msg111_;
          } else {
            result.msg111_ = helloFromServerBuilder_.build();
          }
        }
        result.msgTimestamp_ = msgTimestamp_;
        result.msg111Case_ = msg111Case_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage) {
          return mergeFrom((edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage other) {
        if (other == edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage.getDefaultInstance()) return this;
        if (other.getMsgTimestamp() != 0L) {
          setMsgTimestamp(other.getMsgTimestamp());
        }
        switch (other.getMsg111Case()) {
          case HELLOTOSERVER: {
            mergeHelloToServer(other.getHelloToServer());
            break;
          }
          case HELLOFROMSERVER: {
            mergeHelloFromServer(other.getHelloFromServer());
            break;
          }
          case MSG111_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msg111Case_ = 0;
      private java.lang.Object msg111_;
      public Msg111Case
          getMsg111Case() {
        return Msg111Case.forNumber(
            msg111Case_);
      }

      public Builder clearMsg111() {
        msg111Case_ = 0;
        msg111_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.Builder, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServerOrBuilder> helloToServerBuilder_;
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
       */
      public boolean hasHelloToServer() {
        return msg111Case_ == 1;
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
       */
      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer getHelloToServer() {
        if (helloToServerBuilder_ == null) {
          if (msg111Case_ == 1) {
            return (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) msg111_;
          }
          return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.getDefaultInstance();
        } else {
          if (msg111Case_ == 1) {
            return helloToServerBuilder_.getMessage();
          }
          return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.getDefaultInstance();
        }
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
       */
      public Builder setHelloToServer(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer value) {
        if (helloToServerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg111_ = value;
          onChanged();
        } else {
          helloToServerBuilder_.setMessage(value);
        }
        msg111Case_ = 1;
        return this;
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
       */
      public Builder setHelloToServer(
          edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.Builder builderForValue) {
        if (helloToServerBuilder_ == null) {
          msg111_ = builderForValue.build();
          onChanged();
        } else {
          helloToServerBuilder_.setMessage(builderForValue.build());
        }
        msg111Case_ = 1;
        return this;
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
       */
      public Builder mergeHelloToServer(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer value) {
        if (helloToServerBuilder_ == null) {
          if (msg111Case_ == 1 &&
              msg111_ != edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.getDefaultInstance()) {
            msg111_ = edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.newBuilder((edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) msg111_)
                .mergeFrom(value).buildPartial();
          } else {
            msg111_ = value;
          }
          onChanged();
        } else {
          if (msg111Case_ == 1) {
            helloToServerBuilder_.mergeFrom(value);
          }
          helloToServerBuilder_.setMessage(value);
        }
        msg111Case_ = 1;
        return this;
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
       */
      public Builder clearHelloToServer() {
        if (helloToServerBuilder_ == null) {
          if (msg111Case_ == 1) {
            msg111Case_ = 0;
            msg111_ = null;
            onChanged();
          }
        } else {
          if (msg111Case_ == 1) {
            msg111Case_ = 0;
            msg111_ = null;
          }
          helloToServerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
       */
      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.Builder getHelloToServerBuilder() {
        return getHelloToServerFieldBuilder().getBuilder();
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
       */
      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServerOrBuilder getHelloToServerOrBuilder() {
        if ((msg111Case_ == 1) && (helloToServerBuilder_ != null)) {
          return helloToServerBuilder_.getMessageOrBuilder();
        } else {
          if (msg111Case_ == 1) {
            return (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) msg111_;
          }
          return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.getDefaultInstance();
        }
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloToServer helloToServer = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.Builder, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServerOrBuilder> 
          getHelloToServerFieldBuilder() {
        if (helloToServerBuilder_ == null) {
          if (!(msg111Case_ == 1)) {
            msg111_ = edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.getDefaultInstance();
          }
          helloToServerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer.Builder, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServerOrBuilder>(
                  (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloToServer) msg111_,
                  getParentForChildren(),
                  isClean());
          msg111_ = null;
        }
        msg111Case_ = 1;
        onChanged();;
        return helloToServerBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.Builder, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServerOrBuilder> helloFromServerBuilder_;
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
       */
      public boolean hasHelloFromServer() {
        return msg111Case_ == 2;
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
       */
      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer getHelloFromServer() {
        if (helloFromServerBuilder_ == null) {
          if (msg111Case_ == 2) {
            return (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) msg111_;
          }
          return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.getDefaultInstance();
        } else {
          if (msg111Case_ == 2) {
            return helloFromServerBuilder_.getMessage();
          }
          return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.getDefaultInstance();
        }
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
       */
      public Builder setHelloFromServer(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer value) {
        if (helloFromServerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg111_ = value;
          onChanged();
        } else {
          helloFromServerBuilder_.setMessage(value);
        }
        msg111Case_ = 2;
        return this;
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
       */
      public Builder setHelloFromServer(
          edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.Builder builderForValue) {
        if (helloFromServerBuilder_ == null) {
          msg111_ = builderForValue.build();
          onChanged();
        } else {
          helloFromServerBuilder_.setMessage(builderForValue.build());
        }
        msg111Case_ = 2;
        return this;
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
       */
      public Builder mergeHelloFromServer(edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer value) {
        if (helloFromServerBuilder_ == null) {
          if (msg111Case_ == 2 &&
              msg111_ != edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.getDefaultInstance()) {
            msg111_ = edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.newBuilder((edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) msg111_)
                .mergeFrom(value).buildPartial();
          } else {
            msg111_ = value;
          }
          onChanged();
        } else {
          if (msg111Case_ == 2) {
            helloFromServerBuilder_.mergeFrom(value);
          }
          helloFromServerBuilder_.setMessage(value);
        }
        msg111Case_ = 2;
        return this;
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
       */
      public Builder clearHelloFromServer() {
        if (helloFromServerBuilder_ == null) {
          if (msg111Case_ == 2) {
            msg111Case_ = 0;
            msg111_ = null;
            onChanged();
          }
        } else {
          if (msg111Case_ == 2) {
            msg111Case_ = 0;
            msg111_ = null;
          }
          helloFromServerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
       */
      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.Builder getHelloFromServerBuilder() {
        return getHelloFromServerFieldBuilder().getBuilder();
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
       */
      public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServerOrBuilder getHelloFromServerOrBuilder() {
        if ((msg111Case_ == 2) && (helloFromServerBuilder_ != null)) {
          return helloFromServerBuilder_.getMessageOrBuilder();
        } else {
          if (msg111Case_ == 2) {
            return (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) msg111_;
          }
          return edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.getDefaultInstance();
        }
      }
      /**
       * <code>.edu.stanford.cs244b.mochi.server.messages.HelloFromServer helloFromServer = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.Builder, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServerOrBuilder> 
          getHelloFromServerFieldBuilder() {
        if (helloFromServerBuilder_ == null) {
          if (!(msg111Case_ == 2)) {
            msg111_ = edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.getDefaultInstance();
          }
          helloFromServerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer.Builder, edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServerOrBuilder>(
                  (edu.stanford.cs244b.mochi.server.messages.MochiProtocol.HelloFromServer) msg111_,
                  getParentForChildren(),
                  isClean());
          msg111_ = null;
        }
        msg111Case_ = 2;
        onChanged();;
        return helloFromServerBuilder_;
      }

      private long msgTimestamp_ ;
      /**
       * <code>int64 msgTimestamp = 3;</code>
       */
      public long getMsgTimestamp() {
        return msgTimestamp_;
      }
      /**
       * <code>int64 msgTimestamp = 3;</code>
       */
      public Builder setMsgTimestamp(long value) {
        
        msgTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msgTimestamp = 3;</code>
       */
      public Builder clearMsgTimestamp() {
        
        msgTimestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:edu.stanford.cs244b.mochi.server.messages.ProtocolMessage)
    }

    // @@protoc_insertion_point(class_scope:edu.stanford.cs244b.mochi.server.messages.ProtocolMessage)
    private static final edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage();
    }

    public static edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtocolMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProtocolMessage>() {
      public ProtocolMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtocolMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtocolMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtocolMessage> getParserForType() {
      return PARSER;
    }

    public edu.stanford.cs244b.mochi.server.messages.MochiProtocol.ProtocolMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_stanford_cs244b_mochi_server_messages_HelloToServer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_stanford_cs244b_mochi_server_messages_HelloToServer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_stanford_cs244b_mochi_server_messages_HelloFromServer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_stanford_cs244b_mochi_server_messages_HelloFromServer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_stanford_cs244b_mochi_server_messages_ProtocolMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_stanford_cs244b_mochi_server_messages_ProtocolMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nKsrc/main/java/edu/stanford/cs244b/moch" +
      "i/server/messages/MochiProtocol.proto\022)e" +
      "du.stanford.cs244b.mochi.server.messages" +
      "\"\034\n\rHelloToServer\022\013\n\003msg\030\001 \001(\t\"1\n\017HelloF" +
      "romServer\022\013\n\003msg\030\001 \001(\t\022\021\n\tclientMsg\030\002 \001(" +
      "\t\"\333\001\n\017ProtocolMessage\022Q\n\rhelloToServer\030\001" +
      " \001(\01328.edu.stanford.cs244b.mochi.server." +
      "messages.HelloToServerH\000\022U\n\017helloFromSer" +
      "ver\030\002 \001(\0132:.edu.stanford.cs244b.mochi.se" +
      "rver.messages.HelloFromServerH\000\022\024\n\014msgTi",
      "mestamp\030\003 \001(\003B\010\n\006msg111B\002H\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_edu_stanford_cs244b_mochi_server_messages_HelloToServer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_stanford_cs244b_mochi_server_messages_HelloToServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_stanford_cs244b_mochi_server_messages_HelloToServer_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_edu_stanford_cs244b_mochi_server_messages_HelloFromServer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_edu_stanford_cs244b_mochi_server_messages_HelloFromServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_stanford_cs244b_mochi_server_messages_HelloFromServer_descriptor,
        new java.lang.String[] { "Msg", "ClientMsg", });
    internal_static_edu_stanford_cs244b_mochi_server_messages_ProtocolMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_edu_stanford_cs244b_mochi_server_messages_ProtocolMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_stanford_cs244b_mochi_server_messages_ProtocolMessage_descriptor,
        new java.lang.String[] { "HelloToServer", "HelloFromServer", "MsgTimestamp", "Msg111", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
